name: "Update Juice Shop ecosystem statistics"

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Collect stats data from github and docker
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run collect
    - name: Get current date
      id: date
      run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: stefanzweifel/git-auto-commit-action@v4.0.0
      with:
        commit_message: "Persist statistics collected on ${{ steps.date.outputs.date }}"
        branch: ${{ github.head_ref }}
        commit_options: '--signoff'
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
  heroku:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [collect]
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
      - name: "Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: juicy-statistics
          heroku_email: bjoern.kimminich@owasp.org
          branch: master
