name: "Update Juice Shop ecosystem statistics"

on: [push]

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - name: "Get current date"
      id: date
      run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: "Check out Git repository"
      uses: actions/checkout@v2
    - name: "Use Node.js 14"
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: "Install stats collector"
      run: npm install
    - name: "Collect statistics"
      run: npm run collect
    - uses: stefanzweifel/git-auto-commit-action@v4.0.0
      with:
        commit_message: "Persist statistics collected on ${{ steps.date.outputs.date }}"
        branch: ${{ github.head_ref }}
        commit_options: '--signoff'
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
  heroku:
    needs: [collect]
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
      - name: "Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: juicy-statistics
          heroku_email: bjoern.kimminich@owasp.org
          branch: master
